# Файл конфигурации для загрузки данных из SQLite в PostgreSQL

sqlite:
  database: "db.sqlite"  # Путь к файлу базы данных SQLite

postgres:
  dbname: "sql-to-postgres-db"  # Имя базы данных
  user: "postgres"              # Имя пользователя
  password: "admin12345"        # Пароль пользователя
  host: "127.0.0.1"             # Хост, где развернута база данных
  port: 5432                    # Порт подключения

logging:
  level: "INFO"  # Уровень логирования: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "app.log"  # Имя файла для логов, если требуется сохранение в файл

data_processing:
  batch_size: 1000  # Размер пакета данных для обработки, если работаете с большими объемами данных
